//
//  LockType+ParsingError.swift
//
//  Created by Gray Campbell.
//  Copyright © 2025 Fetch.
//

import Foundation

extension LockType {

    /// A parsing error generated by ``LockType``.
    enum ParsingError: CaseIterable, CustomStringConvertible, Equatable, Error {

        // MARK: Cases

        /// An error indicating that ``LockType`` was unable to parse a valid
        /// instance from the provided macro argument.
        case unableToParseLockType

        // MARK: Properties

        /// The description of the error.
        var description: String {
            switch self {
            case .unableToParseLockType:
                "Unable to parse lock type."
            }
        }
    }
}
